### YamlMime:ModuleUnit
uid: learn.data-ai.transform-data-with-azure-stream-analytics.configure-job-input
title: Exercise - Configure the Azure Stream Analytics job input
metadata:
  title: Exercise - Configure the Azure Stream Analytics job input
  description: Exercise - Configure the Azure Stream Analytics job input
  ms.date: 01/31/2019
  author: ctesta-oneillmsft
  ms.author: chris.testaoneill
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 6a754b7c24f998220e6cccce006b2e6e755b7acd
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
durationInMinutes: 5
content: '[!include[](includes/4-configure-job-input.md)]'
