### YamlMime:ModuleUnit
uid: learn.capture-page-load-times-application-insights.3-exercise-enable-application-insights
title: Exercise - Enable Application Insights on an Azure web app
metadata:
  title: Exercise - Enable Application Insights on an Azure web app
  description: How to enable Application Insights for an existing Azure web app.
  ms.date: 01/08/2019
  author: adrianstevens
  ms.author: adrianstevens
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: b8dc592e1c03533bab8db2dc99e960563c3ead4b
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
azureSandbox: true
durationInMinutes: 10
content: >
  [!include[](includes/3-exercise-enable-application-insights.md)]
tasks:
- action: exists
  environment: azure
  azure:
    resource:
      type: Microsoft.Web/sites
  hint: Review the Complete the web app creation section.
- action: exists
  environment: azure
  azure:
    resource:
      type: microsoft.insights/components
  hint: Review the Enable Application Insights for the web app section.
