### YamlMime:ModuleUnit
uid: learn.performing-text-analytics-with-azure-databricks.5-cleanup-the-environment
metadata:
  title: Cleanup the environment
  description: Cleanup and terminate Azure resources used by this lab.
  ms.date: 02/20/2019
  author: barlanmsft
  ms.author: barlan
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: febcf0d37d7947cc86631f0cb5b46fd74a28497f
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
title: Cleanup the environment
durationInMinutes: 2
content: '[!include[](includes/5-cleanup-the-environment.md)]'
