### YamlMime:ModuleUnit
uid: learn.principles-cloud-computing.4-cloud-deployment-models
title: Cloud deployment models
metadata:
  title: Cloud deployment models
  description: Cloud deployment models
  ms.date: 12/20/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 613b8965e3ef142b84f9dc3a54af87a3794a679a
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
durationInMinutes: 10
content: '[!include[](includes/4-cloud-deployment-models.md)]'
