### YamlMime:ModuleUnit
uid: learn.instrument-web-app-code-with-application-insights.2-install-application-insights-sdk
title: Install, configure, and initialize the Application Insights SDK
metadata:
  title: Install, configure, and initialize the Application Insights SDK
  description: In this unit, you'll learn why and how to install and activate the Application Insights server-side SDK in a web app.
  ms.date: 02/27/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 78844da387831b164239f36a6b6d6c29ed522e47
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
durationInMinutes: 7
content: '[!include[](includes/2-install-application-insights-sdk.md)]'
