### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: Create an Azure IoT Central application
metadata:
  title: Create an Azure IoT Central application
  description: Create an Azure IoT Central application
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 1c131e1bb1b76f0f0c6690a64c907a14180597bc
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
