### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: Configure rules and actions to monitor your coffee machine
metadata:
  title: Configure rules and actions to monitor your coffee machine
  description: Configure rules and actions to monitor your coffee machine
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: c98024366534419b914677bcd998e1b4e0a69a12
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
durationInMinutes: 12
content: '[!include[](includes/5-configure-rules-and-actions.md)]'
