### YamlMime:ModuleUnit
uid: learn-wwl.app-and-infra-migration-and-modernization.5-application-modernization
title: Application modernization
metadata:
  title: Application modernization
  description: Application modernization
  ms.date: 01/31/2019
  author: maargued
  ms.author: maargued
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 9fdc3bc4c7245939932fd6e7b158fc99c81aee4e
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
durationInMinutes: 5
content: '[!include[](includes/5-Application-modernization.md)]'
