### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: Set environment variables
  description: Set environment variables in Azure Container Instances.
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: 852eaa00760e0f6933b4449f7f1378d997bb03b0
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
title: Set environment variables
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: >
  [!include[](includes/4-use-environment-variables.md)]
tasks:
- action: exists
  environment: azure
  azure:
    resource:
      type: Microsoft.ContainerInstance/containerGroups
      name: aci-demo
  hint: ''
- action: exists
  environment: azure
  azure:
    resource:
      type: Microsoft.ContainerInstance/containerGroups
      name: aci-demo-secure
  hint: ''
- action: exists
  environment: azure
  azure:
    resource:
      type: Microsoft.DocumentDB/databaseAccounts
      kind: GlobalDocumentDB
  hint: ''
