### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.10-exercise-connect-with-your-azure-storage-configuration
title: Exercise - Connect with your Azure Storage configuration
metadata:
  title: Connect with your Azure Storage configuration
  description: Connect with your Azure Storage configuration
  ms.date: 01/15/2019
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  zone_pivot_groups: dev-lang-csharp-javascript
  ms.openlocfilehash: 98744a5d48b1a2a8301d9f169dc82ced600f6f9a
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
interactive: bash-editor
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/10-exercise-connect-with-your-azure-storage-configuration.md)]'
