### YamlMime:ModuleUnit
uid: learn.azure.capture-application-logs-app-service.4-view-live-application-logging-activity-with-the-log-streaming-service
title: View Live Application Logging with the Log Streaming Service
metadata:
  title: View Live Application Logging with the Log Streaming Service
  description: View Live Application Logging with the Log Streaming Service
  ms.date: 03/20/2019
  author: nickwalkmsft
  ms.author: nickwalk
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ROBOTS: NOINDEX
  ms.openlocfilehash: c358b6985926d1fea713df6f77ea25aaacc80c7f
  ms.sourcegitcommit: 
  ms.translationtype: MT
  ms.contentlocale: zh-CN
  ms.lasthandoff: 04/24/2019
  ms.locfileid: ''
durationInMinutes: 5
content: '[!include[](includes/4-view-live-application-logging-activity-with-the-log-streaming-service.md)]'
